### ISSUE TITLE
Use a class here instead and add that class to all these elements

### ISSUE THREAD

**Issue by jdorf** [cheffuller/website#3]
https://github.com/cheffuller/websiteTesting/blob/d85d2fd33c4108a4444a308088daa141ee575ef6/style.css#L398

In general, use very few `id`s. I generally will try to use only a single one at the top level element of whatever chunk of html i'm styling. From there, if I need to add specificity I just prefix w/ that id `#randomId .random-class` if I want to be careful about isolation.

Here I would make sure that I even need all of those to have ids and that classnames wouldn't serve you better, then I would add an additional classname to all these places which you would use here in the media query

```
@media (max-width: 576px) {
    ... 
    .new-classname {
    text-align: center;
    border: none;
    padding: 20px 0px;
    ...
     }
  }```

**Comment by cheffuller** [comment]
That makes sense.

The id's used here in this section are for the resume which needed very specific styling in the full-page view. This was from one of our first assignments which was replicating the styling of an example resume (pdf) with css -

[exampleResume.pdf](https://github.com/cheffuller/websiteTesting/files/11579631/exampleResume.pdf)

The best way I knew to apply the different border styling elements to each section was with the id's. They do all share a classname but when I used that it didn't override the id specific styling used to recreate the border style from the example.
